FROM mcr.microsoft.com/devcontainers/python:0-3.11


COPY ca_bundle.crt /usr/local/share/ca-certificates
RUN update-ca-certificates

COPY requirements.txt /tmp/pip-tmp/
RUN pip3 --proxy=http://web.prod.proxy.cargill.com:4300\
  --disable-pip-version-check \
  --trusted-host pypi.python.org \
  --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \
  && rm -rf /tmp/pip-tmp

WORKDIR /app
COPY app/ ./

EXPOSE 8000
ENTRYPOINT [ "uvicorn", "--reload", "--host", "0.0.0.0", "fastapi_server:app" ]


```
 => [3/7] RUN update-ca-certificates                                                                                                                                                                             1.3s 
 => [4/7] COPY requirements.txt /tmp/pip-tmp/                                                                                                                                                                    0.0s 
 => ERROR [5/7] RUN pip3 --proxy=http://web.prod.proxy.cargill.com:4300  --disable-pip-version-check   --trusted-host pypi.python.org   --no-cache-dir install -r /tmp/pip-tmp/requirements.txt   && rm -rf /t  36.5s 
------
 > [5/7] RUN pip3 --proxy=http://web.prod.proxy.cargill.com:4300  --disable-pip-version-check   --trusted-host pypi.python.org   --no-cache-dir install -r /tmp/pip-tmp/requirements.txt   && rm -rf /tmp/pip-tmp:    
#0 9.525 WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)'))': /simple/llama-cpp-python/
#0 10.30 WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)'))': /simple/llama-cpp-python/
#0 11.63 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)'))': /simple/llama-cpp-python/
#0 13.92 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)'))': /simple/llama-cpp-python/
#0 26.40 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)'))': /simple/llama-cpp-python/
#0 36.42 ERROR: Could not find a version that satisfies the requirement llama-cpp-python (from versions: none)
#0 36.43 ERROR: No matching distribution found for llama-cpp-python
------
failed to solve: executor failed running [/bin/sh -c pip3 --proxy=http://web.prod.proxy.cargill.com:4300  --disable-pip-version-check   --trusted-host pypi.python.org   --no-cache-dir install -r /tmp/pip-tmp/requirements.txt   && rm -rf /tmp/pip-tmp]: exit code: 1

 *  The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command docker compose -f "docker-compose.yml" up -d --build" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
 ```
 => ERROR [5/7] RUN pip3 --proxy=http://web.prod.proxy.cargill.com:4300  --disable-pip-version-check   --trusted-host pypi.python.org   --cert /usr/local/share/ca-certificates/ca_bundle.crt   --no-cache-dir  25.2s 
------
 > [5/7] RUN pip3 --proxy=http://web.prod.proxy.cargill.com:4300  --disable-pip-version-check   --trusted-host pypi.python.org   --cert /usr/local/share/ca-certificates/ca_bundle.crt   --no-cache-dir install -r /tmp/pip-tmp/requirements.txt   && rm -rf /tmp/pip-tmp:
#0 10.37 Collecting llama-cpp-python (from -r /tmp/pip-tmp/requirements.txt (line 1))
#0 16.13   Downloading llama_cpp_python-0.1.65.tar.gz (1.5 MB)
#0 16.49      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 4.7 MB/s eta 0:00:00
#0 16.63   Installing build dependencies: started
#0 25.07   Installing build dependencies: finished with status 'error'
#0 25.08   error: subprocess-exited-with-error
#0 25.08
#0 25.08   × pip subprocess to install build dependencies did not run successfully.
#0 25.08   │ exit code: 1
#0 25.08   ╰─> [7 lines of output]
#0 25.08       WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fce24f7a390>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
#0 25.08       WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fce24f85050>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
#0 25.08       WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fce24f85a10>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
#0 25.08       WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fce24f86510>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
#0 25.08       WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fce24f87110>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
#0 25.08       ERROR: Could not find a version that satisfies the requirement setuptools>=42 (from versions: none)
#0 25.08       ERROR: No matching distribution found for setuptools>=42
#0 25.08       [end of output]
#0 25.08
#0 25.08   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 25.08 error: subprocess-exited-with-error
#0 25.08
#0 25.08 × pip subprocess to install build dependencies did not run successfully.
#0 25.08 │ exit code: 1
#0 25.08 ╰─> See above for output.
#0 25.08
#0 25.08 note: This error originates from a subprocess, and is likely not a problem with pip.
------
failed to solve: executor failed running [/bin/sh -c pip3 --proxy=http://web.prod.proxy.cargill.com:4300  --disable-pip-version-check   --trusted-host pypi.python.org   --cert /usr/local/share/ca-certificates/ca_bundle.crt   --no-cache-dir install -r /tmp/pip-tmp/requirements.txt   && rm -rf /tmp/pip-tmp]: exit code: 1
